
const httpUrl = 'https://www.zjcoldcloud.com/xiandun/public/index.php'
const httpUrlapi = 'https://www.zjcoldcloud.com/xiandun/api'
const httpUrlback = 'https://www.zjcoldcloud.com/xiandun_back/public/index.php'
export default {
  reqDevData: httpUrlapi+'/01_00_tb_history_data.php',
  reqDevCharts: httpUrlapi+'/09_00_tb_draw_line.php',
  reqUnbindDev: httpUrl + '/index/Device/remove_bind',
  reqUnbind: httpUrl + '/index/register/unbundle',
  reqDevList: httpUrlback + '/index/device/device_list',
  reqLookDev: httpUrl + '/index/index/look_device',
  reqAddMember: httpUrl + '/index/share',
  reqMemberList: httpUrl + '/index/share/membersList',
  reqSendCode: httpUrl + '/index/register/sendCode',
  reqSendCodeLogin: httpUrl + '/index/login/sendCode',
  reqRegister: httpUrl + '/index/register/add',
  reqOpenid: httpUrl,
  reqLogin: httpUrl + '/index/login',
  reqBindDev: httpUrl + '/index/Device/bind_device',
  reqBindDevice: httpUrl + '/index/device/xiandun_bind_device',
  reqVerifyRegister: httpUrl + '/index/register/verify_user',
  reqBillList: httpUrl + '/index/pay_bill',
  reqEditMember: httpUrl + '/index/share/edit',
  reqDeleteMember: httpUrl + '/index/share/delete',
  reqDevParams: httpUrl+'/index/device/get_device_param',
  reqSetParams: httpUrlback + '/index/device/update_device',
  reqCheckSmsCode: httpUrl + '/index/register/yanzheng_code',
  reqJudgeBinded: httpUrl + '/index/device/remove_scend_device',
  reqUpdateMobile: httpUrl + '/index/register/xiaochengxu_update_phone',
  reqUpload: httpUrl + '/bluetooth/index/index',
  reqBluetoothList: httpUrl + '/index/device/device_blue_tooth_list',
  reqPrinter: httpUrl + '/index/device/printingInfo',
  reqJudgeBluetoothName: httpUrl + '/index/device/bandEquipment',
  reqBluetoothNameExist: httpUrl + '/index/Device/bandEquipmentCheck',
  reqUserDataList: httpUrl + '/index/device/userDataList',
  reqUserDataInfoList: httpUrl + '/index/device/userDataInfoList',
  reqSetRemarks:httpUrl+'/index/device/updateDevice',
  reqDiagram: httpUrl + '/index/device/getDiagram',
  reqShowchart:httpUrl+'/index/device/getDiagram',
  reqPrintInfo:httpUrlback+'/index/device/deviceInfo',
  reqLogin:httpUrl+'/index/login/appletslogin',
  reqLogout:httpUrl+'/index/login/appletsLogout',
  reqForgetpwd:httpUrl+'/index/register/forget_pwd',
  reqDevShare:httpUrl+'/index/device/device_list_for_share',
  reqAddSharemember:httpUrl+'/index/share/add_member',
  reqEditSharemember:httpUrl+'/index/share/edit',
  reqDevListVb:httpUrl+'/index/device/device_list_v1',
  reqDertList:httpUrl+'/index/department/my_department',
  reqWarningList:httpUrl+'/index/alarm/device_list',
  reqUserInfo:httpUrl+'/index/admin/adminInfo',
  reqUpdateUserInfo:httpUrlback+'/index/admin/adminUpdate',
}